services:
  maria-db:
    container_name: dbase
    build:
      context: ./requirements/mariadb/
    image: dbase
    volumes:
      - db:/var/lib/mysql
    networks:
      - back-end
    env_file:
      - .env
    secrets:
      - db_root_pass
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
    depends_on:
      - maria-db
    image: wp
    volumes:
      - wp:/var/www/html
    networks:
      - back-end
      - front-end
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    container_name: ngx
    build:
      context: ./requirements/nginx
    depends_on:
      - wordpress
    image: nginx
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    networks:
      - front-end
    restart: unless-stopped


networks:
  front-end:
    name: front-end
    driver: bridge
  back-end:
    name: back-end
    driver: bridge

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/apaterno/data/wordpress
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/apaterno/data/db
      o: bind

secrets:
  db_root_pass:
    file: ../secrets/db_root_pass.txt
    

